version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: zookeeper
      POSTGRES_PASSWORD: testpass123
      POSTGRES_USER: postgres
    ports:
      - '3500:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: mikelopster
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: always

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  mongodb_master_data:
  postgres_data:
