version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: zookeeper
      POSTGRES_PASSWORD: testpass123
      POSTGRES_USER: postgres
    ports:
      - 3500:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    environment:
      RABBITMQ_DEFAULT_USER: mikelopster
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always


  # gateway:
  #   build: 
  #     context: .
  #     dockerfile: './apps/gateway/Dockerfile'
  #     target: development
  #   command: npm run start:dev gateway
  #   environment:
  #     HELLO: helloworld