version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: mikelopster
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: always

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

  # gateway-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/gateway/Dockerfile
  #   environment:
  #     NODE_ENV: production
  #     AT_SECRET: AFA9C871D7C6ACD3D9DA62D47DDA5
  #     RT_SECRET: 3A21D1D8DF367F68D4199CD2DE3B5
  #     PORT: 3000
  #     AUTH_SERVICE_URL: http://auth-service:5002
  #     KEY_SERVICE_URL: http://key-service:5005
  #     ORDERS_SERVICE_URL: http://orders-service:5004
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - backend
  #   ports:
  #     - '4000:3000'

  # amqp-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/amqp/Dockerfile
  #   environment:
  #     RABBIT_MQ_URL: amqp://mikelopster:password@rabbitmq:5672
  #     MAIL_SERVICE_URL: http://mail-service:5001
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - backend

  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #   environment:
  #     AT_SECRET: AFA9C871D7C6ACD3D9DA62D47DDA5
  #     RT_SECRET: 3A21D1D8DF367F68D4199CD2DE3B5
  #     REDIS_URL: redis
  #     RABBIT_MQ_URL: amqp://mikelopster:password@rabbitmq:5672
  #     GRPC_URL: localhost:5002
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_master_data:
  postgres_data:
